# os stuff

# hostname
- copy: content={{inventory_hostname}} dest=/etc/hostname
- command: hostname {{inventory_hostname}}
  changed_when: False
- template: src=hosts dest=/etc/hosts

# firewall stuff and packages
- name: Upgrade packages
  apt: upgrade=yes update_cache=yes
  tags:
  - slow
- apt: name=iptables state=present
- apt: name=ferm state=present
- file: path=/etc/ferm owner=root group=root mode=0700 state=directory
- template: src=ferm.conf dest=/etc/ferm/ferm.conf owner=root group=root mode=600
  notify:
  - reload firewall
- service: name=ferm state=started enabled=yes
  changed_when: False

# swap
- command: dd if=/dev/zero of=/swap bs=1024 count=1048576 creates=/swap

- name: Change swap file permissions
  file: path=/swap
        owner=root
        group=root
        mode=0600

- name: Check swap file type
  command: file /swap
  register: swapfile
  changed_when: False

- name: Make swap file
  command: mkswap /swap
  when: swapfile.stdout.find('swap file') == -1

- name: Write swap entry in fstab
  mount: name=none
         src=/swap
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: swapon /swap
  when: ansible_swaptotal_mb < 1

# global stuff that should happen only once
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest
- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'
- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- replace: 
    name: update SHA256SUM to 161 
    path: /var/lib/dpkg/info/oracle-java8-installer.postinst
    regexp: 'SHA256SUM_TGZ="c78200ce409367b296ec39be4427f020e2c585470c4eed01021feada576f027f"'
    replace: 'SHA256SUM_TGZ="6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"'
- replace: 
    name: update PARTNER_URL to 161 
    path: /var/lib/dpkg/info/oracle-java8-installer.postinst
    regexp: 'PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/'
    replace: 'PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/'
- replace: 
    name: update JAVA_VERSION to 161 
    path: /var/lib/dpkg/info/oracle-java8-installer.postinst
    regexp: 'JAVA_VERSION=8u151'
    replace: 'JAVA_VERSION=8u161'
- replace: 
    name: update J_DIR to 161 
    path: /var/lib/dpkg/info/oracle-java8-installer.postinst
    regexp: 'J_DIR=jdk1.8.0_151'
    replace: 'J_DIR=jdk1.8.0_161'
- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
- apt: name=runit state=present

# automated updates
#XXX: this potentially conflicts with the mailserver automated updates - TODO: make the mailserver ones off by default, update this to send emails (like the mailserver ones) to some useful email address
- apt: name=unattended-upgrades state=present
- copy: src=apt-periodic dest=/etc/apt/apt.conf.d/10periodic mode=644

